### ISSUE TITLE
Module needs a warning 

### ISSUE THREAD

**Issue by Fishrock123** [yargs/set-blocking#2]
Node has async writes for various reasons stated in https://github.com/nodejs/node/issues/6456

e.g. this bit of background:

> A bit of background: some years ago, I think it was in v0.7, it was decided to make stdout and stderr blocking. Turns out it doesn't work so well for pipes; ttys and files are usually very fast (local ones anyway) but pipes tend to fill up rapidly.
> 
> A number of people complained about it so we made stdio-to-pipe non-blocking again (except on Windows, where it's not supported.) I forgot the exact bug reports but the theme was that stdio was too slow; on OS X, the kernel pipe buffer is only about 4 kB, so it's easy to max out.
> 
> I believe the issue is now that people complain that output sometimes goes missing at program exit. Ideally, we'd have some way to tell libuv "flush only stdio writes, don't do other I/O" but that may not be straightforward to implement.

This should be avoided as much as possible. People **need** to know to only use this module if necessary. I fear this is going to hurt downstream things when these checks are forgotten about in the future. Node core is already working on this now, there's not much we can do. It may be safer to suggest not using v6 until the problem is resolved.

**Comment by Fishrock123** [comment]
@bcoe ^^^

**Comment by bcoe** [comment]
@Fishrock123 I will add a section to the docs with a background, and a word of warning.
