### ISSUE TITLE
May not work on windows (unconfirmed)

### ISSUE THREAD

**Issue by Fishrock123** [yargs/set-blocking#5]
See https://github.com/nodejs/node/pull/6816#issuecomment-220452182

> Setting the blocking mode on windows is only supported for pipes - not for console output.

That being said, I'm interpreting it as a no-op. So it _shouldn't_ break anything? I hope??

**Comment by bcoe** [comment]
@Fishrock123 I think we're cool, and it's a noop:

https://ci.appveyor.com/project/bcoe/yargs

^ yargs is using `set-blocking` in its tests.
